stderr of test 'pyapi29` in directory 'sql/backends/monet5` itself:


# 14:25:18 >  
# 14:25:18 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=37152" "--set" "monet_prompt=" "--forcemito" "--dbpath=/export/scratch2/raasveld/build/var/MonetDB/mTests_sql_backends_monet5" "--set" "embedded_r=yes" "--set" "embedded_py=true"
# 14:25:18 >  

# builtin opt 	gdk_dbpath = /export/scratch2/raasveld/build/var/monetdb5/dbfarm/demo
# builtin opt 	gdk_debug = 0
# builtin opt 	gdk_vmtrim = no
# builtin opt 	monet_prompt = >
# builtin opt 	monet_daemon = no
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 37152
# cmdline opt 	monet_prompt = 
# cmdline opt 	gdk_dbpath = /export/scratch2/raasveld/build/var/MonetDB/mTests_sql_backends_monet5
# cmdline opt 	embedded_r = yes
# cmdline opt 	embedded_py = true
# cmdline opt 	gdk_debug = 536870922

# 14:25:19 >  
# 14:25:19 >  "mclient" "-lsql" "-ftest" "-Eutf-8" "-i" "-e" "--host=lyon" "--port=37152"
# 14:25:19 >  

MAPI  = (monetdb) /var/tmp/mtest-23452/.s.monetdb.39765
QUERY = SELECT * FROM myfunc();
ERROR = !Python exception
        !
        !  1. def pyfun(_columns,_column_types,_conn):
        !> 2.   res = _conn.execute("SELECT max(d) FROM mytable;")
        !  3.   result = dict()
        !  4.   result['n'] = str(res)
        !Loopback queries are not supported in parallel.
CODE  = PY000
MAPI  = (monetdb) /var/tmp/mtest-11032/.s.monetdb.32138
QUERY = DROP TABLE mytable;
ERROR = !Current transaction is aborted (please ROLLBACK)
CODE  = 25005
MAPI  = (monetdb) /var/tmp/mtest-11032/.s.monetdb.32138
QUERY = DROP FUNCTION myfunc;
ERROR = !Current transaction is aborted (please ROLLBACK)
CODE  = 25005

# 14:25:20 >  
# 14:25:20 >  "Done."
# 14:25:20 >  

